name: "DEMO: Deploy Application to Azure"

on:
  workflow_dispatch:
  
permissions:
  id-token: write
  contents: read
    
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: DEMO
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.1.0
    
    - name: "Log into container registry"
      uses: azure/docker-login@v1
      with:
        login-server: ${{ vars.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build Docker images
      run: docker compose build --build-arg NUGET_API_USER=${{ secrets.NUGET_API_USER }} --build-arg NUGET_API_KEY=${{ secrets.NUGET_API_KEY }}
      env:
        IMAGE_TAG: ${{ github.sha }}
        REGISTRY_URL: ${{ vars.REGISTRY_URL }}

    - name: Push Docker images
      run: docker compose push
      env:
        IMAGE_TAG: ${{ github.sha }}
        REGISTRY_URL: ${{ vars.REGISTRY_URL }}
  
    - name: "Deploy to Azure Web App"
      uses: "azure/webapps-deploy@v2"
      with:
        app-name: app-rts-demo-rt-clientportal-api-eastus2
        images: ${{ vars.REGISTRY_URL }}rt-clientportal-api:${{ github.sha }}
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}
